name: Publish

on:
  push:
    branches: [master]
    paths:
      - 'build-logic/**'
      - 'lib/**'
      - '.github/workflows/publish.yml'

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - name: Fetch source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android environment
        uses: android-actions/setup-android@v3

      - name: Install Android NDK
        run: |
          sdkmanager --install "cmake;3.22.1"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install extra-cmake-modules gettext

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish build convention and libs
        run: |
          ./gradlew :build-logic:convention:publish
          ./gradlew :lib:common:publish
          ./gradlew :lib:plugin-base:publish

